URL_TO_MONITOR = "www.skipq.org"
URL_MONITOR_NAMESPACE = "SikandarWebHealth"
URL_MONITOR_NAME_AVAILABILITY = "url availibility"
URL_MONITOR_NAME_LATENCY = "url latency"
ALARM_THRESHOLDS = [0.27, 0.22, 0.2, 0.8]
